Gem security integration
Gem-Security/cortex-xsoar pull request #1
Opened 2024-03-17 09:37 UTC by liormgem

## Contributing to Cortex XSOAR Content
Make sure to register your contribution by filling the [contribution registration form](https://forms.gle/XDfxU4E61ZwEESSMA)

**The Pull Request will be reviewed only after the contribution registration form is filled.**

## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: link to the issue

## Description
A few sentences describing the overall goals of the pull request's commits.

## Must have
- [ ] Tests
- [ ] Documentation

2024-03-18 19:22 UTC, danielxt7 requested changes
Initial pass - looks great! see few comments 🥸

2024-03-18 19:22 UTC, danielxt7 commented on Packs/Gem/Scripts/ResolveGemAlert/ResolveGemAlert.yml
> +comment: "Post Processing Script that will resolve the relevant Alert in the Gem platform."
Alert or Threat? the script itself uses the threat resolve API no?

2024-03-19 08:49 UTC, liormgem commented on Packs/Gem/Classifiers/classifier-GemAlert.json
> +    "version": -1,
That's the way to use it.
All the examples and the other packs do that:
https://xsoar.pan.dev/docs/incidents/incident-classification-mapping

2024-03-19 08:50 UTC, liormgem commented on Packs/Gem/Integrations/Gem/Gem_description.md
> +  - **Maximum number of alerts per fetch:** The number of alerts to fetch in every run, when using the pull integration method instead of real-time. Default value is 10
Every chunk
That's the convention in case the integration is fetching

2024-03-19 08:51 UTC, liormgem commented on Packs/Gem/Scripts/ResolveGemAlert/ResolveGemAlert.yml
> +comment: "Post Processing Script that will resolve the relevant Alert in the Gem platform."
True, changing

2024-03-19 08:52 UTC, liormgem commented on Packs/Gem/Classifiers/classifier-mapper-incoming-Gem-webhook.json
> +    "version": -1
Same

2024-03-19 14:49 UTC, danielxt7 approved these changes
great stuff!!! see few minor comments 🚀 🚀 🚀

2024-03-19 14:49 UTC, danielxt7 commented on Packs/Gem/Integrations/Gem/Gem.py
> +            params={k: v for k, v in params.items() if v is not None}
the param extraction patterns has 9 occurrences `gem.py` :) - consider extracting to a helper func? something like `_filter_non_empty_params` or similar

2024-03-19 14:49 UTC, danielxt7 commented on Packs/Gem/Integrations/Gem/Gem.py
> +    for _ in range(0, int(max_results / PAGE_SIZE) + 1):
this is different from the iteration in `list_threats` - `range(1, int(max_results / PAGE_SIZE) + 2)` - which is correct? :)

2024-03-19 15:20 UTC, liormgem commented on Packs/Gem/Integrations/Gem/Gem.py
> +    for _ in range(0, int(max_results / PAGE_SIZE) + 1):
Both are using different Endpoint with different paginations
So both are correct

2024-03-19 15:38 UTC, merged